name: Welcome!

on: 
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  write-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/first-interaction@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello! Thank you for filing an issue.

            If this is a bug report, please include relevant logs to help us debug the problem.
          pr-message: |
            Hello! Thank you for your contribution.
            
            If you are fixing a bug, please reference the issue number in the description
